# Generated by Django 5.1 on 2024-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='place_id',
            field=models.CharField(max_length=255),
        ),
    ]
