# Generated by Django 5.1.1 on 2024-10-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_alter_favorite_name_alter_favorite_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
